# Generated by Django 5.1.5 on 2025-02-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'verbose_name_plural': 'Raw Materials'},
        ),
        migrations.AlterModelOptions(
            name='saree',
            options={'verbose_name_plural': 'Sarees'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
